:hosts:
  - :host: ec2-184-72-81-42.compute-1.amazonaws.com
    :port: 80
    :secret: FCo7t7397E5k46s
    :secure: false

# :hosts:
#   - :host: 127.0.0.1
#     :port: 8080
#     :secret: FCo7t7397E5k46s
#     :secure: false
